---
version: "3.8"

services:
  frontend:
    image: my-frontend-image:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    networks:
      - app-network

  backend:
    image: my-backend-image:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://user:password@my-rds-instance:3306/bingo-db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
