version: "2"

services:
  frontend:
    image: my-frontend-image:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000

  backend:
    image: my-backend-image:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://user:password@database:3306/mydb

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
