version: "3.7"

services:
  frontend:
    image: my-frontend-image:latest  # Replace with your frontend image
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    logging:
      driver: awslogs
      options:
        awslogs-group: my-ecs-logs
        awslogs-region: ap-southeast-1
        awslogs-stream-prefix: frontend

  backend:
    image: my-backend-image:latest  # Replace with your backend image
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://user:password@database:3306/mydb
    logging:
      driver: awslogs
      options:
        awslogs-group: my-ecs-logs
        awslogs-region: ap-southeast-1
        awslogs-stream-prefix: backend

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    logging:
      driver: awslogs
      options:
        awslogs-group: my-ecs-logs
        awslogs-region: ap-southeast-1
        awslogs-stream-prefix: database

volumes:
  db-data:

