version: '3.0'

services:
  frontend:
    image: 124355652898.dkr.ecr.ap-southeast-1.amazonaws.com/frontend-repo:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    image: 124355652898.dkr.ecr.ap-southeast-1.amazonaws.com/backend-repo:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL} # Ensure this is set in AWS SSM or ECS secrets
    depends_on:
      - database

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge
