name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ECS CLI
        run: |
          sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          sudo chmod +x /usr/local/bin/ecs-cli
          ecs-cli --version

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-1'

      - name: Check ECS Cluster
        run: |
          aws ecs describe-clusters --clusters bingo-ecs-cluster-c702d43 --region ap-southeast-1 || \
          aws ecs create-cluster --cluster-name bingo-ecs-cluster-c702d43 --region ap-southeast-1

      - name: Ensure IAM Role is Attached to EC2 Instances
        run: |
          INSTANCE_IDS=$(aws ec2 describe-instances --filters "Name=tag:aws:autoscaling:groupName,Values=bingo-ecs-asg" --query "Reservations[*].Instances[*].InstanceId" --output text)

          if [ -n "$INSTANCE_IDS" ]; then
            for INSTANCE_ID in $INSTANCE_IDS; do
              aws iam attach-role-policy --role-name ecsInstanceRole \
                --policy-arn arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
            done
          else
            echo "No ECS instances found in the ASG."
          fi

      - name: Configure ECS Cluster
        run: |
          ecs-cli configure --cluster bingo-ecs-cluster-c702d43 \
            --default-launch-type EC2 \
            --config-name bingo-config \
            --region ap-southeast-1

      - name: Deploy to ECS
        run: |
          ecs-cli compose --file docker-compose.yml --cluster bingo-ecs-cluster-c702d43 --region ap-southeast-1 up
