name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ECS CLI
        run: |
          sudo curl -Lo /usr/local/bin/ecs-cli \
          https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          sudo chmod +x /usr/local/bin/ecs-cli
          ecs-cli --version

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-1'

      - name: Check ECS Cluster
        run: |
          aws ecs describe-clusters --clusters bingo-ecs-cluster-c702d43 \
          --region ap-southeast-1 || \
          aws ecs create-cluster --cluster-name bingo-ecs-cluster-c702d43 \
          --region ap-southeast-1

      - name: Configure ECS CLI
        run: |
          ecs-cli configure --cluster bingo-ecs-cluster-c702d43 \
          --default-launch-type FARGATE \
          --config-name bingo-config \
          --region ap-southeast-1

      - name: Deploy to ECS
        run: |
          ecs-cli compose --file docker-compose.yml \
          --project-name bingo-app \
          --cluster bingo-ecs-cluster-c702d43 \
          --region ap-southeast-1 up
